/* DO NOT EDIT THIS FILE - it is machine generated */
#include "ac_iitm_htic_simplenativedaemon_cpp.h"


#if defined(__BIONIC__)
#include "sys/system_properties.h"

#endif



JNIEXPORT jobject JNICALL
Java_ac_iitm_htic_simplenativedaemon_cpp_b(JNIEnv *env, jclass type, jobject p) {

    // TODO
    if(p)
        __system_property_set("myprop.test", "1");
    else
        __system_property_set("myprop.test", "0");

    return p;

}




