/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ac_iitm_htic_simplenativedaemon_cpp */

#ifndef _Included_ac_iitm_htic_simplenativedaemon_cpp
#define _Included_ac_iitm_htic_simplenativedaemon_cpp
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     ac_iitm_htic_simplenativedaemon_cpp
 * Method:    b
 * Signature: (Ljava/lang/Boolean;)Ljava/lang/Boolean;
 */
JNIEXPORT jobject JNICALL Java_ac_iitm_htic_simplenativedaemon_cpp_b
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
