/* DO NOT EDIT THIS FILE - it is machine generated */
#include "ac_iitm_htic_simplenativedaemon_cpp.h"
/* Header for class ac_iitm_htic_simplenativedaemon_cpp */


JNIEXPORT jobject jboolean Java_ac_iitm_htic_simplenativedaemon_cpp_b
  (JNIEnv *je, jclass jc, jboolean s){
        static void setService(JNIEnv *env, jclass clazz, jboolean s) {
                if(s)
                    property_set("myprop.test", "1");
                else
                    property_set("myprop.test", "0");

        }
        }


#ifdef __cplusplus
}
#endif
#endif
